$(document).ready(function(){
	
	$('#intcorgi').fadeIn(1500);
	$('#intcorgi').delay(1000).fadeOut(1000);
	$('#cselect').delay(3500).slideDown("medium");
	$('#pdetails').delay(3500).slideDown("medium");



	var framehold = $("#framehold");
	var doverlay = $("#dark");
	var about = $('#pabout');
	var pDetails = $('#projbdy');
	var pic = $('#ppic');
	var pTitle = $("#projtitle");
	var closepre = $("#closebtn");
	var mksong = $('#mksong')[0];


	playSong();

	//p = project (what the user clicks on), t = title, v = details, i = image
	function Project(p, t, v, i, l){
		this.p = p;
		this.t = t;
		this.v = v;
		this.i = i;
		this.l = l;		

		p.click(function() {
				//p.css("border", "3px solid red");
				pic.empty();
				pTitle.text(t);
				pDetails.text(v);
				pic.css("background-image", i);

				pic.click(function(){
					closepre.fadeIn(500);
					framehold.fadeIn(500);
					doverlay.fadeTo("slow", 0.5).css("background-color", "black");
					framehold.html("<iframe height = '500px' width = '500px' src = '"+l+"'>")
				})

				closepre.click(function(){
					framehold.fadeOut(500);
					doverlay.fadeOut("fast");
					closepre.fadeOut(500);

				})
			
		})
	
	}


	var businessPg = new Project ($('#businesspg'), 
		"Business Page", 
		"This page was a practice run for creating a business page.  It's a static website with no real features, mostly serving as a testing-ground for CSS development.",
		"url(img/business1.jpg)", 
		"http://cawley90.github.io/BusinessPage/");

	var theList = new Project ($('#thelist'), 
		"The List", "'The List' was a project I worked on that delved a bit more into scripting pages to make them a bit more dynamic.  It was the first time I had really worked on adding new elements to the chage as per user choice, changing them, and removing them as well.", 
		"url(img/list1.jpg)", 
		"http://cawley90.github.io/TheList/");

	var quiz = new Project ($('#quiz'), 
		"Internetiquette Quiz", 
		"This online quiz was a huge experiment into object oriented scripting.  Instead of creating different pages or elements for each question and appropriate answers, I strived to keep everyting centralized in one little function.  Every time a user answers a question, the question counter goes up and prints out the next challenge as per the array.  It was a huge success for me and works great!", 
		"url(img/quiz1.jpg)",
		"http://cawley90.github.io/Quiz/");

	var sfighter = new Project ($('#sfighter'), 
		"Street Figher", 
		"This little Street Fighter page was the result of me starting to learn jQuery.  Half the project was already completed to help me get a head start, it's more there as a bit of fun than anything.  But the concepts I learned from this project really helped me understand jQuery a bit more.", 
		"url(img/sf1.jpg)",
		"http://cawley90.github.io/jquery-streetfighter/");

	var fetch = new Project ($('#fetch'), 
		"FetchIt", 
		"FetchIt was really one of my first actual projects.  The projects on here were following a certain criterea, FetchIt was my own little thing.  Using Json, Javascript, jQuery, and AJAX, you can use FetchIt to grab the most relevant Youtube video according to what you're searching for.  It grabs the video itself, video title, author, views, and likes.  You can also grab a link for the video, as well as loop whatever video you're searching for.  It's great for quickly searching for something, or listening to the same song as many times as you'd like.  It's also a great way to find new videos.", 
		"url(img/fetch1.jpg)",
		"http://www.charonsdirge.com/fetchit/");

	var hotCold = new Project ($('#hotcold'), 
		"Hot/Cold", 
		"The Hot or Cold game was a project working on how to take a user value and comparing it with a value generated by a math function.  Its value - again - was basically learning how to compare things.  It doesn't sound like much, but it was a huge cause for headaches for the beginner me.", 
		"url(img/hc1.jpg)",
		"http://cawley90.github.io/hot-or-cold-starter/");

	var stackJx = new Project ($('#stackajax'), 
		"Stacker Ajax", 
		"This Stack Overflow rep builder was mostly just a page built to prove theories using AJAX.  It was a good experience to learn more about using APIs and how crazy they can be.  The practical functionality of the project is beyond me other than finding similar queries on Stack Overflow, but I don't really use that website very often.  They're always yelling at you for asking stupid questions despite being a website about answering questions.  It's like, chill out guys.", 
		"url(img/sa1.jpg)",
		"http://33.media.tumblr.com/49ccab810ac67aa0789c952cf621222e/tumblr_n58edskCkS1txc4ylo1_400.gif");




	$('#pause').click(function() {
		//mksong.pause();

		if (mksong.paused == false) {
			mksong.pause();
		} else {
			mksong.play();
			mksong.volume = 0.2;
		}
	})

	function mkIn() {
		if ($("#cselect").css("display") == "none") {
			$("#changcont > div").fadeOut("fast");
			$("#cselect").fadeIn("fast");
			$("#pdetails").fadeIn("fast");
		}

	}


	function mkOut() {
		$("#pdetails").fadeOut("fast");
		$("#cselect").fadeOut("fast");
	}

	$("#folio").click(mkIn);


	$("#me").click(function(){
		mkIn();
		pic.css("background-image", "url(img/thisguy.jpg");
		pTitle.text("About This Guy");
		pDetails.text("My name is Chris, and I am the creator of this page and all pages enclosed.  I'm part dog trainer (suddenly all the Corgis are explained), part front end web developer - albeit an amateur.  I can't stress that last part enough.  This portfolio marks the end of a course I've taken in front end development, but there's many more steps for me to take.  Keep your eyes on the internet, the Corgis are coming.");

	})


	$("#aboutbtn").click(function(){
		mkOut();
		$("#aboutpage").fadeIn("fast");
	})


});

	function playSong () {
	mksong.volume = 0.2;
	mksong.play();

}